### ISSUE TITLE
rawlog format?

### ISSUE THREAD

**Issue by pammirato** [jotaraul/HOMe-Toolkit#2]
HI,

I am not a roboticist, but a computer vision researcher. I am not familar with the rawlog format.

All I have is a bunch of time stamped rgb/depth images, and camera parameters. Can I convert this to rawlog to use your tool?  (I mostly want to find the position of the robot at each image).

If not, what should I do next time to capture my data in the rawlog format?

I don't want to waste too much of your time, a link or two to a place explaining how to capture rawlog data would be great. (I am familar with ROS)

**Comment by jlblancoc** [comment]
Hi, 

[Rawlog](http://www.mrpt.org/Rawlog_Format) is like ROS rosbag in the [MRPT framework](http://www.mrpt.org)... is was invented because in 2005 when we started MRPT, ROS was still to born (~2008)! ;-)

Perhaps @jotaraul could port his code to use the [mrpt::hwdrivers::CCamera](http://reference.mrpt.org/stable/classmrpt_1_1hwdrivers_1_1_c_camera_sensor.html) instead of reading from a Rawlog file directly?? It will allow reading images from any live camera, a rawlog or a directory with images, by just changing the `grabber_type` parameter in the CCamera config file (it must not be an actual file, it can be created on-the-fly as a [CConfigFileMemory](http://reference.mrpt.org/devel/classmrpt_1_1utils_1_1_c_config_file_memory.html), for example, as requested from some command-line arguments, etc.

my two cents ;-)

**Comment by jotaraul** [comment]
Hi!

As jlblancoc said, the rawlog format is quite similar to rosbag. Given that you have already the MRPT library, it is quite easy to get data in that format. You just need to use the <a href="http://www.mrpt.org/list-of-mrpt-apps/application-rawlog-grabber/">Rawlog grabber application</a>, which needs a configuration file to set the sensors to be used to get the data and tehir configuration. Luckily, MRPT also comes with a number of configuration file examples, that you can find in mrpt\share\mrpt\config_files\rawlog-grabber .

To JL: I know that it's possible to play rawlog files in ROS (http://wiki.ros.org/mrpt_rawlog), but is there a way to "convert" a rosbag file to rawlog?

Regarding the CCamera option, it looks nice, I'll put that into the (huge) TODO list :+1: .

**Comment by jlblancoc** [comment]
You can play a rosbag, then record it with `rawlog_record_node` (it already existed but was not mentioned in [the wiki](http://wiki.ros.org/mrpt_rawlog), sorry!). 

Anyway, those nodes are fairly simple so far and only record/play laser scans and odometry, if I remember it right...

**Comment by jotaraul** [comment]
Hope this "conversation" helped! Reopen if needed.
